# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Product Philosophy"
description: > # this means to ignore newlines until "email:"
   Useful tips about managing software products

email: magdalena2019@gmail.com
#blog logo
logo: "/assets/images/MM_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Magdalena Murphy'
author: 'Magdalena Murphy'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://magdamurphy.github.io" # the base hostname & protocol for your site
baseurl: "/magda-blog"
#used to display twitter cards

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/magdalena-murphy-761a363b
    desc: Add me on LinkedIn
    share_url: https://www.linkedin.com
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
